project:
  type: book

book:
  title: "Version Control for Data Analysis"
  subtitle: "at Sheffield City Council"
  author: "Laurie Platt"
  date: last-modified
  date-format: "DD MMMM, YYYY"
  chapters:
    - index.qmd
    - intro.qmd
    - status.qmd
    - gitignore.qmd
    - references.qmd
  downloads: pdf
  favicon: resources/git.svg

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  freeze: auto