project:
  type: book

book:
  title: "Version Control for Data Analysis"
  subtitle: "at Sheffield City Council"
  author: "Laurie Platt"
  date: last-modified
  date-format: "DD MMMM, YYYY"
  repo-url: https://github.com/scc-pi/version-control
  chapters:
    - index.qmd
    - intro.qmd
    - data-protection.qmd  
    - training.qmd  
    - code-reviews.qmd  
    - anonymise.qmd  
    - gitignore.qmd  
    - repo-template.qmd  
    - git-hooks.qmd  
    - secrets.qmd  
    - publish-check.qmd 
    - github-roles.qmd  
    - breach-protocol.qmd
    - references.qmd
  downloads: pdf
  favicon: resources/git.svg

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    #documentclass: krantz
    
execute:
  freeze: auto