# Training

Version control is not especially difficult, but the risks will be greatest when someone is new to it. The low number of potential users of version control for data analysis means that bespoke Go Learn style training is not justified. Instead, there should be some training from an existing Council user of GitHub. This is in addition to personal responsibility for reading the Council guidance and undertaking specified, openly available, introductory training courses on Git and GitHub.  

## GitHub  

| Introduction to GitHub and GitHub Skills are good places to get started and become familiar with some initial concepts:  
| [github.com/skills/introduction-to-github](https://github.com/skills/introduction-to-github)  
| [skills.github.com](https://skills.github.com/)

[Version Control with Git and SVN](https://support.rstudio.com/hc/en-us/articles/200532077?version=1.4.1103&mode=desktop), Posit Support  
[Ch.4 Version control with Git, Building reproducible analytical pipelines with R](https://raps-with-r.dev/git.html), by Bruno Rodrigues  

## ToDo  